### ISSUE TITLE
[feature] Clearing console

### ISSUE THREAD

**Issue by revelt** [jsbin/issues#1]
Hi Remy, 
It's not a bug a feature hint.
We should add a way to clear the console in mode JavaScript->Console. 
Maybe ESC key could be repurposed?
Or, at least, we should have a way to distinguish old console log's from the current, so it's clear which output is still relevant. I really like the live evaluation but it's not entirely clear is the last line really current. That's my only "pain point" with v5.
cheers
👍

**Comment by remy** [comment]
Have you tried the universal `ctrl+l` or `console.clear()` - both work on the jsbin console and your native console.

**Comment by revelt** [comment]
Aha! Didn't know that. Feel free to close then. 💯

**Comment by remy** [comment]
👍

**Comment by Dayjo** [comment]
@remy Just FYI, on the Alpha version for me, `ctrl+l ` doesn't do anything. `console.clear()` works but it's a bit faffy typing it out everytime. Is there a special dark place for Alpha bugs?
