### ISSUE TITLE
Old version Please

### ISSUE THREAD

**Issue by fabianobezerra** [jsbin/issues#19]
I would like to use the old version of JSBIN, this version v5.0.0-alpha.32, it's horrible.
my browser does not see the previous version

**Comment by remy** [comment]
"horrible". Sorry, there's a command in 5 to revert but I don't feel like helping right now. Sorry. You'll find it I'm sure...or not...

**Comment by fabianobezerra** [comment]
> "horrible". Sorry, there's a command in 5 to revert but I don't feel like helping right now. Sorry. You'll find it I'm sure...or not...

Hello I managed to clear the browser cache, but this version has no option to vote for the old one.
