### ISSUE TITLE
Unable to open multiple tabs

### ISSUE THREAD

**Issue by edmundcjj** [jsbin/issues#3]
This new version does not have the function where multiple tabs can be selected and viewed and worked on the same time.

**Comment by remy** [comment]
That's correct and by design.

**Comment by edmundcjj** [comment]
Then how do I work on html, css and javascript simultaneously in the new version?

**Comment by remy** [comment]
Unless I'm mistaken, you can only type into a single text field at a time.

However, you're able to code in HTML, then switch to CSS then switch to JavaScript using the "Source" selector:

<img width="628" alt="screen shot 2018-03-07 at 12 04 46" src="https://user-images.githubusercontent.com/13700/37091360-bf04f658-21ff-11e8-87f1-a9ef283e608a.png">

Or the keyboard shortcuts provided.
