### ISSUE TITLE
can go back to the old jsbin

### ISSUE THREAD

**Issue by ymele** [jsbin/issues#34]
i want to go back to my work but it's impossible and i want to go back to the old présentation of JSbin it was easier and im familiar to it; but i can i dont know how to.

**Comment by remy** [comment]
Impossible? Then why are you asking.

Or, maybe it's in the menu?

<img width="1239" alt="Screenshot 2020-07-13 at 20 39 40" src="https://user-images.githubusercontent.com/13700/87346107-0a0b0400-c549-11ea-8054-0c5cf134fac4.png">
