### ISSUE TITLE
If I press any where in the screen the text deleted appears

### ISSUE THREAD

**Issue by ash20light** [jsbin/issues#38]

**Comment by remy** [comment]
By "press" do you mean from a touch based device?

**Comment by ash20light** [comment]
Yes

**Comment by ash20light** [comment]
Kindly help

**Comment by remy** [comment]
Touch and mobile is not supported as yet. I suggest you downgrade to v4 - it has better mobile support

**Comment by ash20light** [comment]
Thankyou
