### ISSUE TITLE
From Alpha.36 to the previous version

### ISSUE THREAD

**Issue by is-burcea** [jsbin/issues#39]
I just started using JSBin and right after loging in i've upgraded to alpha 36, but the course I'm taking is based on the previous version and I can't find many features in the alpha version. 

How can I turn back to the original version, the one with the logo in the left corner? Thank you.

**Comment by Bhumital94** [comment]
I have same issue ...

**Comment by remy** [comment]
It's in the menu: https://github.com/jsbin/issues/issues/34
