### ISSUE TITLE
WHAT! NEW JSBIN = TRASH!

### ISSUE THREAD

**Issue by JackFarrell** [jsbin/issues#40]
WHAT HAPPENED!  I went into my website's code and said "whoops! This is bla bla bla bla"  The NEW jsbin doesn't have a "my bins"! Once your code and close the tab you lose all of it!  I WANT OLD JSBIN BACK!

**Comment by remy** [comment]
Thanks for your opinion. I was going to tell you how to revert but since you're being a dick, I think I'd rather not.
