### ISSUE TITLE
Not be able to save and share my code in jsbin

### ISSUE THREAD

**Issue by KaranNajwani** [jsbin/issues#5]
The older version of jsbin was good. These vesion have so many problems i could not find menu bar in my homepage where i can save and share my code easily as well as when i tried to save my code in jsbin by using there command it couldn't work. In earlier i used it and i easily share my code with others but these was radiculous  please improved it otherwise it will not be useful for us.

**Comment by remy** [comment]
I'm sorry this doesn't suit your preferences. Of course there are other *free* tools available for you. 

Going to close as I can't see any specific bug other than new jsbin not being to your taste.

**Comment by remy** [comment]
(for reference, there is not menu bar)
