### ISSUE TITLE
OUTPUT IS NOT SHOWING!!

### ISSUE THREAD

**Issue by aryanaryasir** [jsbin/issues#53]
output is not showing in the output area

![Screenshot 2024-05-12 195525](https://github.com/jsbin/issues/assets/86570216/ee332b0d-e0f6-4994-b5dd-d82b4a3cdd07)

**Comment by aryanaryasir** [comment]
IF ANYBODY CAN FIX IT PLEASE LET ME KNOW!

**Comment by remy** [comment]
THERE IS NO CONTENT TO SHOW. PUT SOME CODE AND THEN YOU'LL SEE SOME OUTPUT. 

NO FIX REQUIRED.

BUT YES, LET'S CAP LOCK LIKE ITS 1999!!!!!!
