### ISSUE TITLE
Can't leave alpha

### ISSUE THREAD

**Issue by ferd-i** [jsbin/issues#6]
Hello,

I've read the blog post announcing jsbin 5 alpha version, it led me to the editor and now, everytime I go to jsbin I have it. I cannot exit the alpha.

**Comment by ferd-i** [comment]
Oh ok my bad, I didn't see the link "go back to the old version". Sorry

**Comment by serhii-horobets** [comment]
Show all commands - Revert to (old) JS bin

**Comment by remy** [comment]
Are there any errors in your browser's native console?
