### ISSUE TITLE
Blank page after loging with Github

### ISSUE THREAD

**Issue by goediaz** [jsbin/issues#7]
Hello.

I logged for the first time using Github and it redirects me to a blank page:

`https://jsbin.com/auth/github/callback?code=0294bdc86e7002a57101`

I tried removed JSBin from Authorized OAuth Apps on Github and log in again but it didn't workes.
When I remove `/auth/github/callback?code=0294bdc86e7002a57101` from the URL it works but the page is weird. 

![image](https://user-images.githubusercontent.com/11638996/39127094-4de76d64-4704-11e8-8454-d5a5fce64e7c.png)

Chrome console doesn't show any erros.

Thanks!

**Comment by goediaz** [comment]
I fixed the issue going back to the 'old' JSBin. Weird but it worked.

**Comment by itselijahciali** [comment]
I have this issue still as well
