### ISSUE TITLE
Save to JS Bin: Created: https://jsbin.com/undefined (alpha)

### ISSUE THREAD

**Issue by SMotaal** [jsbin/issues#9]
Sadly saving to JS Bin never works. For the few months I tested alpha, so far I've been able to save locally, gist, and can't even remember how CodePen worked but sure it was less functional or else I would have opt for it instead of gists.

A few months in, I wanted to verify that Save to JS Bin is actually not yet implemented and not a bug.

Please let me know if I can provide more input. 👍

**Comment by remy** [comment]
Can you give this a retest? I noticed the same thing bug fixed the end
point mid-last week.

**Comment by SMotaal** [comment]
I cleared caches and tried in both Safari and Chrome still no luck.

<details><summary>Safari</summary>

```apl
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
	dispatchException (main.6eeda05b.js:1:138063)
	(anonymous function) (main.6eeda05b.js:1:134649)
	r (app.76221c2e.chunk.js:1:308625)
	(anonymous function) (app.76221c2e.chunk.js:1:308745)
	promiseReactionJob
```

</details>

<details><summary>Chrome</summary>

```apl
06:39:07.132 api.jsbin.com/bin:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

</details>

**Comment by SMotaal** [comment]
I got it working in Chrome 👍 

- Deleted saved JS Bin chrome app
- Deleted all storage (except for IndexDB)

**Comment by remy** [comment]
Sod, also try to visit jsbin.com/login - it might be your token expired (a
bug)

**Comment by SMotaal** [comment]
With `jsbin.com/login` the token issue is solved but as soon as I hit settings then the footer shows `Sign in v5.0.0-alpha.32` which I think relates to the cause which prevents `"app.syncSettings"` from kicking in because it is never really saved except in LocalStorage
